version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: fintech_db
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech_dev_password
      POSTGRES_DB: fintech_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintech"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for caching and task queue)
  redis:
    image: redis:7-alpine
    container_name: fintech_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend (optional - can run locally)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: fintech_backend
  #   environment:
  #     DATABASE_URL: postgresql://fintech:fintech_dev_password@db:5432/fintech_tracker
  #     REDIS_URL: redis://redis:6379
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
